# -*- coding: utf-8 -*-
"""investment_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHNOY_pcGlhCiRBHatFPb1u19-Mabae5
"""

def get_recommendation():
  while True:
    try:
      salary = int(input("\nEnter your monthly salary (positive number only): "))
      if salary <= 0:
        print("Salary must be greater than 0. Please try again.")
        continue
      break
    except ValueError:
      print("Invalid input. Please enter a numeric value.")

    #Using 50,30,20 Rule
    #50% - Expenses
    #30% - Savings
    #20% - Invest

    expense = salary*0.50
    savings = salary*0.30
    investable_amt = salary*0.20

    print("\nBased on your salary, here is a suggested plan: ")
    print(f"Essential expenses: Rs.{expense:.2f}")
    print(f"Savings: Rs.{savings:.2f}")
    print(f"Amount available for Investment: Rs.{investable_amt:.2f}")

    #Ask user's risk preference
    print("\nWhat is your risk preference?")
    print("1. Low Risk")
    print("2. Moderate Risk")
    print("3. High Risk")
    risk_choice = input("Enter 1,2 or 3: ")

    #Mapping risk choice to categories
    risk_map = {
        "1": ["Low Risk", "Low Moderate Risk"],
        "2": ["Moderate Risk", "Low Moderate Risk"],
        "3": ["High Risk", "Moderate Risk"]
        }
    selected_risks = risk_map.get(risk_choice, ["Low Risk"])

    #Creating investment options
    options = {
        "FD": ("Low Risk", "5-6% return", "1-5 years"),
        "Mutual Funds": ("Moderate Risk", "8-12% return", "3.5 years"),
        "Gold ETF": ("Low Moderate Risk", "7-10% return", "1-2 years"),
        "Stocks": ("High Risk", "12-20% return", "Long term")
        }

    print("\nAvailable Investment Options:")
    for name, details in options.items():
      print(f"-{name}: Risk = {details[0]}, Return = {details[1]}, Duration = {details[2]}")

    print("\nRecommended Options for you based on your risk preference:")
    recommended = False
    for name, details in options.items():
      if details[0] in selected_risks:
        print(f" -{name} - Risk = {details[0]}, Expected Return = {details[1]}, Duration = {details[2]}")
        recommended = True

    if not recommended:
      print("No suitable investment options found for your selected risk preference.")

    #Additional guidance
    print("\nAdditional Guidance based on your investable amount: ")
    if investable_amt<3000:
        print("FD or Gold ETF-safer and suitable for small monthly investments.")
    elif investable_amt<100000:
        print("Mutual Funds - balanced returns with moderate risk.")
    else:
        print("Stocks + Mutual Funds - good for higher investment capacity.")

#Menu Structure
print("Welcome to the Financial Investment Recommender")

while True:
    print("\nMenu:")
    print("1. Get Recommendation")
    print("2. About for Users")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
      while True:
        get_recommendation()
        another = input("\Do you want another recommendation? (yes/no):").strip().lower()
        if another != "yes":
          break
    elif choice == "2":
       print("\nTo use this program, simply enter your monthly income when prompted. Based on your input, the system will guide you on how much you can invest")
       print("and will also recommend the best investment options by comparing their risk level, expected returns and duration.")
       print("The suggestions are easy to understand and are designed to help women make smarter, confident and independent financial decisions.\n")
    elif choice == "3":
       print("\nThank you for using the Financial Investment Recommender. Have a great day!")
       break

    else:
       print("Invalid choice. Please try again.")